git:
  depth: 1

matrix:
  include:

    - os: linux
      language: cpp
      sudo: false
      dist: bionic
      addons:
        apt:
          packages:
            - qttools5-dev
            - qtmultimedia5-dev

      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .
        
