name: Build Rclone Browser

on:
  push:
  workflow_dispatch:
  
jobs:
  build_windows:
    name: Windows Build
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Install Development Tools
        run: choco install visualstudio2019community visualstudio2019-workload-nativedesktop cmake qt5-default -y 
      - name: Build Rclone Browser
        run: |
          cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_CONFIGURATION_TYPES="Release" -DCMAKE_PREFIX_PATH=c:\Qt\5.15.2\msvc2017_64 .. 
          cmake --build . --config Release
          C:\Qt\5.15.2\msvc2017_64\bin\windeployqt.exe --no-translations --no-angle --no-compiler-runtime --no-svg ".\build\Release\RcloneBrowser.exe"
      - uses: actions/upload-artifact@v3
        with:
          name: RcloneBrowser.exe
          path: .\build\Release\RcloneBrowser.exe
          
  build_linux:
    name: Linux Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Install Development Tools
        run: |
          sudo apt update
          sudo apt -y install git g++ cmake make qtdeclarative5-dev qtmultimedia5-dev
      - name: Build Rclone Browser
        run: |
          mkdir build
          cd build
          cmake ..
          make -j $(nproc)
          ### TODO: Upload the artifact when we know where it lives
          ls
         
  build_macos:
    name: macOS Build
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Install Development Tools
        run: brew install git cmake rclone qt5
      - name: 
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH:PATH=/usr/local/opt/qt5
          make -j $(nproc)
          cd build
          /usr/local/opt/qt@5/bin/macdeployqt rclone-browser.app -executable="rclone-browser.app/Contents/MacOS/rclone-browser" -qmldir=../src/
          mv rclone-browser.app Rclone\ Browser.app
          zip -r -0 Rclone\ Browser.zip Rclone\ Browser.app
      - uses: actions/upload-artifact@v3
        with:
          name: Rclone Browser (macOS)
          path: build/build/*.zip
        
    
